language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule --debug destroy
before_install:
- openssl aes-256-cbc -K $encrypted_3d8635d61624_key -iv $encrypted_3d8635d61624_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
env:
  global:
  - secure: i1T+RCC2z3XKuHPFTE4VoUUmnpL2mOu2Z/MqMR9LHUf6bkx9x7P6LH/cf6Ae4bKPpZ4xOeAVg4B3KQ0A/3G6DQOjF2umf2y83243xNDn4+dd875RmzzsevW5spT545x5BRAB4i6kLjJzrtS04BgAnP1MGjlHURW7n6poYzC/bCYt4CfFYv34sUNUJeGWmhkly11NEmHww5hjzhcVgI6jGqavrXA/m6xSQvZ787aewiJTyzv74WTvB6jeJIBr8llCL49lUUJ86G5G7n+tlTv29P7RbcAKIFxGldEPWVN+KOeSl4sV6iyyrH0z979Cek2ZqAfa3bRNICDiJvbBrOt9m5UX78E/3Jt6vFbCb28tHQx14pWn37lCanTdFFSzn7sCpwTeXD6DZeX6qD+1230s+uyPqD1+Yn/YrizZr24/bJGAo3DVg6PUz/8hdzdlJJ22VJpnMVTq1A+Z72IzW9BuCAqonVcaawPY6kSHrQHfvKLz86teH+W72sv0QYhNnj3b8ELxIn2BdHL3cVPNyIlOHFZ0eoJ81dO5IrtseP5kg4yaO6F7agrz/+aNdOQvqlClKtO6GAenMeZwq4I5g8QWI+JDqAuxA9F/OVttt3oXebE6OWwRm4RAZAcnLu9MHIBE2GEpWi9VPVtpfSyCtwn50JdfTGl17XRlZ0A/uktJzKI=
  - secure: mW/QCMGZ2WvaL4Nq78tcDGJbRux65RurYw7R8T2MVsdWnQgxjUbDHFhdVQ7q/h3IP8b1I2guRpUVmp9YzwG2zi73uJYCtlfGw7quHjkOqxtXO0xEoFa9Bw/Zqr3+0p30UwrDCNEcxC5fwXVjB9OVGF1UvYwJ9uGq8UiCE0W6o8w387AvCTEwAkrpXPq1w5FeBeHt++uZFuYE584/OnumwGOtzAUPFQquVX6v0WDXGtfKvmEIWZuW44j4KBTUrwdYBRh6zgyVMFV2DHO7ijrVCPSMkovDKCFD6SX+RlqtIz6wJHI7AxdAps6Cvia5+TfENGlrgBtZRYsAi8D+TLnlaxfw+zI/FTJ9bAnsVf/urv965wnoWibVXUU5EqFaasRC0oNV4wYmAqg5thIpoDsEkur4oRfIHLnbfEvU1JBpOPz9Zqi2KCPtEful02nqGdgYThVmmHlkXUBi4LpthaxBo0yp7Np848BH2+P3BdMt6Rku9qecXOXnr87s7C8WpPj6fHP0CBh4fisf/Gl8SDND+AJqQIrlonrMz6AzZe+ZCgbi4but7z75XNkzVASGFDWjNUvzujvz54SSPOTwFDDR4FDPi7+7ESZmK3MheROZTj50XDTgu9YNZiKnpLhLaBalAWMfA730T5UIMsMuCv37AtUGhvqZYlNpjZVES0/jpq0=
  - secure: AeoIJu4O4+IvuNY1gmLEK2L0ujWIcRtrG3/qiMZSg7ot9p+rSlaYugKrT+UwIvJ8NbJqOUBdUQpNT81n4Ziu40JtofxVL6qeEEFsQtq6jT13rWIftEa2+8b7HCIq9RHEL14+CC6qfAy42Y74zE7HvBKLiddMelZIRXMDGV3BxpcSa4CEtn2TqCZxcQh6cnypIiq4PbI2MlSmyjvkz8vsdqhENXxtLNUchKQF7uUslKw6lYxPLdREigt9CTSXCa148rUNeF32uP39q8fe7ELOXwV7YpfhdYDncCJjtQOcU83s8kAixsZ+b1Nc3VAydCeuWR3BVPcdY2QKJx4lIYoKGpWK9byeXizTvB/gfgvzRqu4aunU/i6TvXrPhMj4ezWH+lWDysEJtN5ABKmb2zdU4zSzgl/ifc4rdgU7WOv3vrX5+LB5v3iuqPIyxl8WjRFVjiDiwRMjJ8VD+ULbl4FZzeqZttkmrOI2vuAUb5RX40EALGVFYkaJwAani2dVeKSx98g6XUFc3gdQlAGf4qCEXnbh+QJ0dJi5zaipcxSePA3PTgychIOSTdWH7tEfjyyTkqYUXGDBbj18Hb2+QLSbAn0oEVC4tSLkDnR/pllPQRTMf3U87msibV50Acxhrs+CsCmwt2+pUXFvdf+Qy9T+vzcV14Sv4w27JMKnFarIuIU=
