language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule --debug destroy
before_install:
- openssl aes-256-cbc -K $encrypted_3d8635d61624_key -iv $encrypted_3d8635d61624_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- echo $GCE_CREDENTIALS_FILE
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
env:
  global:
  - secure: lV0Sgkd4O0dSjM7r1Ow4nXo4h8YtyXUqF3njhFLt5JCMK1pS6uKMNaTweAxLX/pdJu0Xmc0dyz4KPQPwplLJLu+kku181AFxBJc2euywS3bnaeRC2qAjfmvVTbrKHm6GzJPxge7MQGQQPJfoIODSVXyYjq3bjR04bVa9sMqFOTJXmw64eqIJYYEV7+gxWqhkkaf9Z7HkAmQM6INav+X1KSTimelwrRFtYHmS4G4SXLN5HJrt2qEgMQCwphjE8AikNIRVte5YS3frJ4s5QOtDJc9Ou11ug7S2po7ld5MhLL8N1x7L/biBv9OYKVYJSzs1K9hmoiRSyBFczLufw0kVLJeDOUhzVESIoFQiuyzv94sp7/edzFBdWEzMMcV9Ruqpz/weWmPWHiCSREGOeGJ8wEBUNxoqKstl+WBRH/3zNmKqc9uWFyB/YOEJYQrjpF4hVZ5SvX0AxCY8lyguEyITrLQCRByMRipRNX0AG4jLFAofmRNjD9mf97/fZ98SFYqbAqzNV6RS+td6HfUFhvuWqiEmFzcTPtteaxbfDf96TkJucLKeW7QtAUBKXcBzWBzjwXUdYX48pHvSOLE8UKFyACgBZjZbM40XBfF7XDHG92SAa8mP8K3Hsryj8hiduDT7/HYYonyhDa2O/bZx63NKCvPSaDVOmF6j4eN5O/0HHHI=
  - secure: HZewKzngDqjdAxtSKejk9qkRuvYZqx/miYPoj0vtoR50MqdTsIy7k9g8Qt6eJNgJ5mMpcFy6ZbxWqqwRg7r9t/KH2J94H/RImt/BhepENI6t+B2UrMrWIWK1ggFAloe3EfqT3hyQyxrlwStKll88YG0NlCX8/v1y3Y59akbfHZvukdhqqYG2zIoc/qHoXEtnSXKHGlUp3oDyGg1p+ILYksIhpso1MszKTEKoqZ3Crq27YcsWCBI51slJrMhIUHHijP/K1FS+Zkz9zUPv8K1xwpYHY9FPcXWm36XD0BHasoA51p9M2+EhCmLKbDb+tgtGvr2V+J8yBVSabk+K9iRLALJsexJwI58HQAZziG3LUxlfQDJMNMxR/ZeUbjpcLxrfqfBTFgpK6293u3ZTlTM+OccbYv0JVBgP1N9Gzt0G+vOW/6dymSQDL98aDTpTVPhabflFSbJN7lGLE/i9QGqqgdZGMhUQ1SwGSSXiR7rgEYshrUlw6xvuF8Dcc4XS8RuCelRs/hL/E8/DMSWnxcjVZLXkWpeYzn+IaAxtFmMD85MYcfk4tj6n9MXflhuTeSGLcXhexmfYGMK4f+572OFngcSpdDnwSsZcoikfufUXCQ0rnwuKi1FA0j72LhWFGoy8QDwzoa39anLDwG09JXqGMBfAnWhplMHgj5S9VfFY0Dc=
  - secure: FHtmp7QF0igULziwag0hf9oJiJ+Hhcd4iwzzOZfIwok0lp8v7k6l8cEqQ3oW6eveElGdSgtICa6ciS0eS3Y8/tcwsjDC7H2VOZndOYFc2Sn8vfOUcy5FtRGO+phf07Xj4A9gdPRkOzEsDrZ8hZ4yBmrzRqeOHXYHj3AMhXGF2E7xbk9nB8h5hBcu54KtQAwsaUbI9S3xemodlC/RAkFSOn+etsG1qFgmY8p5SWGS+3zIgMFGd2a6FsRa8qEqxmfR887eH9a6wHRjya6sdaPcmFVe/5XhYi8Q+ah1gmeKLexhuwvO+uNX7WEbiqyKxbzFOH2XsHCLrGMd1emagkIPJ2kpbOMxvJTPxYzUWa5w/Lnrvm+ZTH5HQ/bECHxkmYfQtKgJg/io7F16MFge0Kf9eF73z65EPHKioFpFPdmytHKSCMJKzPHEvDx4xjTkKO80YXD8NVD0hTTegpc7ff+QgH2QPliCkCYrfiM/gg96Clx0ckPFy0APPAqD0bTVRrRDJR775U7J/ZczW3Rk109vQnI2u3il/FBcgrHcnYZ1uzosq+kGt5JArON/ZOI5FIJAZv+39pEGlDb53Nw/LzAjZXLnkPqHAguyR81EGyV1kZlOvHWb33INT7gOSExlEB6xO19fSa1NMAan9xezDoDE5c1CwnBzhfbdA7cO5zzA/F8=
