language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule --debug destroy
before_install:
- openssl aes-256-cbc -K $encrypted_3d8635d61624_key -iv $encrypted_3d8635d61624_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
env:
  global:
  - secure: Ce6C5GH6P5tHm62OIHQH8drPGS0V2Xn71RKeZQ1vFDtuOu8rXYM2dOMVFondShJr1DN2ZXUOEl0hEDH1Y7rwdrA3Kl7tvOMrSsW6kf64s/cxMEqEtI9POOj0lMxctd4lQ5jPr+ppEy7fbqE+kaG9G7yLaeUVF46cmMHRnYvX2qW57SQMbpObovja9aNIiaOtFlf8PwVOFNK+SHK6fKe4v8yqO6mRC2OLkGIEKrh4LaTP6LgdjBzkI1GGzLQZ16++DMLRL/Bgxx4vEkb/a82zfdR7hkGlfqCV0ixL+HWbokhnlTnP/peMHZmCwqOuLCDZsKNHFrsAY93vQuSFkANLiBB82q3TZ4yX6hTzLON3uL/uj0QcnMkYApY7ud1mRCoIZjbyxvJTGKf9PGN/L++HGIuREJ2aqGkpjPOqGzAaWdqa60zE8m8QQg8a7p5lz15zr4DyGmZvEFhXvoZuiqbgIPpawtzOvYbmhEg/EhB0eaqiGtRxvO2HI1Rt+ez6GZYJvh6uhQiRZKuaSVKJlYtpQcO1Al8mB97fsy1If3U7HsX10WDkXCVuMAgD9pfOAl/fVxD3mfsh4IKDyEsBkjmbGjlOltB8DerP39av+hpr2f/Yc6twyQSctg7/Jk1c13CRXGJ0dvEwNetK8UX12ewaAn6zMbDwEMYDpd5djK/LWYg=
  - secure: LmylG+zcP4wlXMsUMl5lFPDESX8uvlIfYp4mCKxyUc4jdvtk2RX8M8+rVzTQBE1u0E3UnKwwQj/ysQZ7VZw/nMxLvre3aBT0FgnKysmAI6xieG8VhBUXTyG41zN6VFgGgN6sm9rPhs3n8OsIfel/HV55p3/QPx1YfvRvYzF8CsuYB4LGImSeyz3BIDxmnZqxcnTVpQiZR82/GqBy4tlNtT1p2IwR0F9dLONAgBzlrlWof52CchQX0hqJ3Ci2wiQqGRPaYXs8ZTcWh0fCtKKueH3oKXU9L7nUyhIA1eat6Bg6YmSu43DyWUhEQboj4De/+vmrjVO+jfe6QW6HCbIZ2ucQgmvBDJm9VkDDp2RImSN1Xg7o2b3fWPMFxqGgWLbJddlIuLLzUlayDw/az/fMViZ3O63RzejdXpo4ZZSYsL0N41xyImj6KX6RrZgfzBnyxxD7TMUx8S596TAahTjbqx8QZT/zzj4hU8age7piJcdlEsfx0+WvPnGv7923LFRpDdP7BiK11GSOBSxdTNxZlZxk3lIalo+bXUislgBSLGq9k6+pGsyj/p2BmWeVub35PXWjGMIoH2afD9pXkDBAtj+cskWb2dQO50ZUdrx1Y5v3dRFrf8YsCQvqwOSm7y/nSrREARcFiNPABEMrtBgXzDTQ/IsQ7BuRnVXut7n4+Nc=
  - secure: He9tZHE1ofQIye3bGKpRmOeMThwDFZMxZEsFbNXm7ADCUGmwKLQJ/x662yBxf/tN82hJoUSWFZovVBG5FQa5BXLUlyNHMm+bb6zLUpmjqwMVI/uSlDYWbLZgR6vIqhX6mMDlQUqa6smCqiruiuyeQontwWF+ErrvL60f2OLphcOFjoe8hrWqgPD09Zjlv9imbB/NTmlYTE4JFQzZUCHqSXU8I0LKWqiWmRciyBGXTxyldKxe2ltcf/gYov8I7005Our85ZrBQKbw0OuVh5vKbVg597ntbVfh6swokiQXh4ALK89bQDwW6P0TiE4NEh+5BXi7Q0jOCEZdIlx8QHjEbKBVikX/f6L2nfS2eTj+F0Y1M7xcV1MmXPgtxFAGQaaIT1pwxJUVUQlfY0yic2vyL/U3KzTC3mN9bTasBQV5kBBr+gNT1IpbT17bx73lfLMfHuEm9e2srNpvzVeCoN6XK8GGSPTIwKZKx1nYTkch6hS6sPleAbPwBurlZh8eVvPoDzx0ZKfnuuVyVrcty3H2+lhicGIuLiUXNZGyXNXgfGHw6erU1dD06TePAdGINAgxjEdV+UIplpEXk3FMonjDKHS0054dsgQ53PSvSDpTmVRQDzmxtK3YIqh7CXUnY13DkIwhgpoEdvzbzpo6sRtND3af+jbQFLWSM8c3sYlkmZ4=
