---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: instance
    zone: us-west1-a
    machine_type: f1-micro
    image_family: ubuntu-1604-lts
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
